server:
  port: 8090

chatbot-assistant:
  # 多组配置 group01,group02
  launchList: group01
  group01:
    groupName: 码农鱼塘
    groupId: 48884842444448
    cookie: zsxq_access_token=F7A63AFE-47E9-1BB8-A0EB-067DF34EB609_4342A9D74B7C9FE7; UM_distinctid=1863943ab39118-08c47fa1f6bb5e-26021051-1fa400-1863943ab3a1149; sensorsdata2015jssdkcross={"distinct_id":"414455411558148","first_id":"1850447de9911e-0305447a34acc6-26021151-2073600-1850447de9ab89","props":{"$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":""},"identities":"eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMTg1MDQ0N2RlOTkxMWUtMDMwNTQ0N2EzNGFjYzYtMjYwMjExNTEtMjA3MzYwMC0xODUwNDQ3ZGU5YWI4OSIsIiRpZGVudGl0eV9sb2dpbl9pZCI6IjQxNDQ1NTQxMTU1ODE0OCJ9","history_login_id":{"name":"$identity_login_id","value":"414455411558148"},"$device_id":"1850447de9911e-0305447a34acc6-26021151-2073600-1850447de9ab89"}; abtest_env=product; zsxqsessionid=4df2d708c23d0191262a3e8abf9cb8df; __cuid=e47353f396c448aeaa9ce910472a39fb; amp_fef1e8=6c44c3aa-16f6-45fa-b36e-1ed7d5dbfbf3R...1gp9q3mds.1gp9q3me5.g.a.q
    openAiKey: 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
    cronExpression: MC8zMCAqICogKiAqID8=
    #cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
  group02:
    groupName: ChatGPT AI 问答助手
    groupId: 28885518425541 # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey:  # 自行申请 https://beta.openai.com/overview 或者联系小傅哥 fustack 付费申请【购买虚拟号码等需要支付】。
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com